import Head from 'next/head';
import '../globals.css';
import Header from '../components/Header';
import BarChart from '../components/BarChart';
import NowPrice from '../components/NowPrice';
import NextHourPrice from '../components/NextHourPrice';
import AverageToday from '../components/AverageToday';
import AverageTomorrow from '../components/AverageTomorrow';

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Next & Tailwind Sidebar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Header />
      </div>
      <main>          
          <div>
            <BarChart  />
          </div>
          <br></br>
          <div className="row">
          <div className="column">
            <div className="card">
              <NowPrice />
            </div>
          </div>
          <div className="column">
            <NextHourPrice />
          </div>
          <div className="column">
            <AverageToday />
          </div>
          <div className="column">
            <AverageTomorrow />
          </div>
        </div>
      </main>
    </>
  );
}